[tool.black]
line-length = 120
target-version = [
  'py38',
  'py39',
  'py310',
  'py311',
  'py312',
  'py313',
]
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.pytest_cache
  | \.github
  | _build
  | build
  | dist
  | venv
  | test/resources
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]